---
- name: Create user
  hosts: all
  become: true
  tasks:
    - name: "Create user"
      ansible.builtin.user:
        name: CHANGEME_USERNAME
        password: "{{ 'password' | password_hash('sha512', 'CHANGEME_PASSOWRD') }}"
        groups:
          - sudo
        state: "present"
        shell: "/bin/bash"
        system: false
        create_home: true
        home: "/home/USERNAME"
        comment: "Ansible root"
        generate_ssh_key: true